#!/usr/bin/python3

# Definition for singly-linked list.
class ListNode:
     def __init__(self, val=0, next=None):
         self.val = val
         self.next = next

class Solution:
    def toList(self, head: [ListNode]) -> []:
        s = []
        if head == None:
            return s
        while (head.next != None):
            s.append(head.val)
            head = head.next
        s.append(head.val)
        return s

    def removeNthFromEnd(self, head: [ListNode], n: int) -> [ListNode]:

# UNIT TESTING #
pino = Solution()

# EXAMPLE 1
#
# Input: lists = [[1,4,5],[1,3,4],[2,6]]
#
[1,2,3,4,5]
2
head = ListNode(1,ListNode(2,ListNode(3,ListNode(4,ListNode(5)))))
n = 2
lists = [ListNode(1,ListNode(4,ListNode(5))), ListNode(1,ListNode(3,ListNode(4))), ListNode(2,ListNode(6))]
res=pino.mergeKLists(lists)
print(pino.toList(res))

# EXAMPLE 2
#
# Input: lists = []
#
[1]
1
lists = []
res=pino.mergeKLists(lists)
print(pino.toList(res))

# EXAMPLE 3
#
# Input: lists = [[]]
#
[1,2]
1
lists = [[]]
res=pino.mergeKLists(lists)
print(pino.toList(res))
